
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listAvailableTemplatesTauri() : Promise<TemplateSummary[]> {
    return await TAURI_INVOKE("list_available_templates_tauri");
},
async listAvailableFragmentsTauri() : Promise<FragmentDefinition[]> {
    return await TAURI_INVOKE("list_available_fragments_tauri");
},
async inspectFragmentTauri(fragmentName: string) : Promise<FragmentDefinition | null> {
    return await TAURI_INVOKE("inspect_fragment_tauri", { fragmentName });
},
async inferSubstituteByFragmentCompletionTauri(molecule: Molecule, selectedAtomId: number) : Promise<SubstituteByFragmentCompletion | null> {
    return await TAURI_INVOKE("infer_substitute_by_fragment_completion_tauri", { molecule, selectedAtomId });
},
async matchFunctionalGroupsTauri(molecule: Molecule) : Promise<FunctionalGroupMatch[]> {
    return await TAURI_INVOKE("match_functional_groups_tauri", { molecule });
},
async orderedBenzeneRingCarbonsTauri(molecule: Molecule) : Promise<number[] | null> {
    return await TAURI_INVOKE("ordered_benzene_ring_carbons_tauri", { molecule });
},
async getInitialAppState() : Promise<AppState> {
    return await TAURI_INVOKE("get_initial_app_state");
},
async applyCommand(state: AppState, command: Command) : Promise<AppState> {
    return await TAURI_INVOKE("apply_command", { state, command });
},
async applyCommands(state: AppState, commands: Command[]) : Promise<AppState> {
    return await TAURI_INVOKE("apply_commands", { state, commands });
},
async parseMoleculeFileTauri(fileName: string, text: string) : Promise<Result<Molecule, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_molecule_file_tauri", { fileName, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderGaussianTauri(spec: ChemicalSpec) : Promise<string> {
    return await TAURI_INVOKE("render_gaussian_tauri", { spec });
},
async validateChemicalSpecTauri(spec: ChemicalSpec) : Promise<ValidationMessage[]> {
    return await TAURI_INVOKE("validate_chemical_spec_tauri", { spec });
},
async buildAiContextTauri(state: AppState) : Promise<AiContext> {
    return await TAURI_INVOKE("build_ai_context_tauri", { state });
},
async proposeCommandsViaAiTauri(input: string, state: AppState, screenshot: string | null) : Promise<Result<AiProposal, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("propose_commands_via_ai_tauri", { input, state, screenshot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planYoloStepsTauri(input: string) : Promise<YoloPlanStep[]> {
    return await TAURI_INVOKE("plan_yolo_steps_tauri", { input });
},
async proposeYoloStepTauri(input: string, state: AppState, screenshot: string | null, plan: YoloPlanStep[], step: YoloPlanStep, history: YoloStepHistoryEntry[]) : Promise<Result<YoloStepProposal, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("propose_yolo_step_tauri", { input, state, screenshot, plan, step, history }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiContext = { selectedAtoms: AtomSummary[]; atomIndexMap: AtomIndexMapEntry[]; atomContextMap: { [key in number]: string }; calculation: CalculationSummary }
export type AiProposal = { commands: Command[]; resolvedCommands: Command[]; explanation: string }
export type AppState = { domain: DomainState; ui: UiState }
export type Atom = { id: number; element: Element; isotope: MassNumber | null; nuclearSpin: TwiceSpin | null; formalCharge?: number; position: [number, number, number] }
export type AtomIndexMapEntry = { displayIndex: number; atomId: number }
export type AtomSummary = { displayIndex: number; element: Element; isotope: MassNumber | null; nuclearSpin: TwiceSpin | null; formalCharge: number; position: [number, number, number]; chemicalContext: string | null }
export type AttachPort = { id: string; portType: PortType; recommendedUsage: string }
export type Basis = "6-31G(d)" | "def2-SVP" | "def2-TZVP"
export type Bond = { id: number; atomIds: [number, number]; order: number }
export type CalculationSpec = { jobType: JobType; method: Method; basis: Basis; solvent: Solvent | null; charge: number; multiplicity: number }
export type CalculationSummary = { jobType: JobType; method: Method; basis: Basis; solvent: Solvent | null; charge: number; multiplicity: number }
export type ChemicalSpec = { molecule: Molecule; calculation: CalculationSpec }
export type Command = { type: "SET_METHOD"; method: Method } | { type: "SET_BASIS"; basis: Basis } | { type: "SET_JOB_TYPE"; job_type: JobType } | { type: "SET_SOLVENT"; solvent: Solvent | null } | { type: "SET_CHARGE"; charge: number } | { type: "SET_MULTIPLICITY"; multiplicity: number } | { type: "SET_BOND_LENGTH"; atom_ids: [number, number]; length: number; mode?: GeometryEditMode } | { type: "SET_BOND_ANGLE"; atom_ids: [number, number, number]; angle: number; mode?: GeometryEditMode } | { type: "SET_DIHEDRAL_ANGLE"; atom_ids: [number, number, number, number]; angle: number; mode?: GeometryEditMode } | { type: "ADD_ATOM"; element: Element; position: [number, number, number]; isotope: MassNumber | null; nuclear_spin: TwiceSpin | null; formal_charge?: number } | { type: "SET_ATOM_FORMAL_CHARGE"; atom_id: number; formal_charge: number } | { type: "DELETE_ATOM"; atom_id: number } | { type: "ADD_BOND"; atom_ids: [number, number]; order: number } | { type: "DELETE_BOND"; bond_id: number } | { type: "PLACE_TEMPLATE"; template_name: string; position: [number, number, number]; direction: [number, number, number] } | { type: "ATTACH_FRAGMENT"; fragment_name: string; target_atom_id: number; rotation_angle: number; orientation: [number, number, number] } | { type: "SUBSTITUTE_BY_FRAGMENT"; fragment_name: string; start_atom_id: number; end_atom_id: number } | { type: "REPLACE_ATOM"; atom_id: number; element: Element } | { type: "SET_MOLECULE"; molecule: Molecule } | { type: "TOGGLE_ATOM_SELECTION"; atom_id: number } | { type: "CLEAR_SELECTION" }
export type DomainState = { chemicalSpec: ChemicalSpec }
export type Element = "H" | "He" | "Li" | "Be" | "B" | "C" | "N" | "O" | "F" | "Ne" | "Na" | "Mg" | "Al" | "Si" | "P" | "S" | "Cl" | "Ar" | "K" | "Ca" | "Sc" | "Ti" | "V" | "Cr" | "Mn" | "Fe" | "Co" | "Ni" | "Cu" | "Zn" | "Ga" | "Ge" | "As" | "Se" | "Br" | "Kr" | "Rb" | "Sr" | "Y" | "Zr" | "Nb" | "Mo" | "Tc" | "Ru" | "Rh" | "Pd" | "Ag" | "Cd" | "In" | "Sn" | "Sb" | "Te" | "I" | "Xe" | "Cs" | "Ba" | "La" | "Ce" | "Pr" | "Nd" | "Pm" | "Sm" | "Eu" | "Gd" | "Tb" | "Dy" | "Ho" | "Er" | "Tm" | "Yb" | "Lu" | "Hf" | "Ta" | "W" | "Re" | "Os" | "Ir" | "Pt" | "Au" | "Hg" | "Tl" | "Pb" | "Bi" | "Po" | "At" | "Rn" | "Fr" | "Ra" | "Ac" | "Th" | "Pa" | "U" | "Np" | "Pu" | "Am" | "Cm" | "Bk" | "Cf" | "Es" | "Fm" | "Md" | "No" | "Lr" | "Rf" | "Db" | "Sg" | "Bh" | "Hs" | "Mt" | "Ds" | "Rg" | "Cn" | "Nh" | "Fl" | "Mc" | "Lv" | "Ts" | "Og"
export type FragmentDefinition = { name: string; displayName: string; description: string; templateName: string; molecule: Molecule; attachPorts: AttachPort[] }
export type FunctionalGroupKind = "benzeneRing" | "carboxylicAcid" | "sulfonicAcid" | "amide" | "nitrile" | "ester" | "aldehyde" | "ketone" | "alcohol" | "amine" | "alkene" | "alkyne" | "ether" | "halogen" | "nitro"
export type FunctionalGroupMatch = { kind: FunctionalGroupKind; atomIds: number[]; attachmentAtomId: number | null; referenceAtomId: number | null }
export type GeometryEditMode = "ATOM_ONLY" | "MOVE_OTHER_SIDE" | "MOVE_BOTH_SIDES"
export type JobType = "opt" | "freq" | "opt+freq" | "ts"
export type MassNumber = number
export type Method = "B3LYP" | "WB97XD"
export type Molecule = { name: string; atoms: Atom[]; bonds: Bond[] }
export type PortType = { atom: { targetId: number } } | { bond: { startAtomId: number; endAtomId: number } }
export type Solvent = "THF" | "Water"
export type SubstituteByFragmentCompletion = { startAtomId: number; endAtomId: number }
export type TemplateSummary = { name: string; displayName: string; description: string }
export type TwiceSpin = number
export type UiState = { selectedAtoms: number[] }
export type ValidationLevel = "error" | "warning"
export type ValidationMessage = { level: ValidationLevel; message: string }
export type YoloPlanStep = { id: number; goal: string }
export type YoloStepHistoryEntry = { stepId: number; goal: string; status: string; explanation: string; commands: Command[] }
export type YoloStepProposal = { prompt: string; commands: Command[]; resolvedCommands: Command[]; explanation: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
